### ISSUE TITLE
站点是挂掉了吗

### ISSUE THREAD

**Issue by yueru** [junwen0301/Announcement#4]
全都访问不了了

**Comment by isakula** [comment]
我这都挂了，官网客服都没了。

**Comment by yueru** [comment]
> 我这都挂了，官网客服都没了。

QQ客服也没反应了，难道跑路了吗

**Comment by isakula** [comment]
😂有没其他推荐的么～

**Comment by sinb** [comment]
我的也全线断了

**Comment by yueru** [comment]
之前找到就这一个比较稳定的了，别的还有什么推荐的吗

**Comment by isakula** [comment]
我在群里问到了一个，https://ss.mluoc.tk/register?aff=271

**Comment by sinb** [comment]
> 我在群里问到了一个，https://ss.mluoc.tk/register?aff=271

钓的一手好鱼，您是钓鱼吧来的吧

**Comment by isakula** [comment]
你说钓鱼就钓鱼吧。

**Comment by Mrcici** [comment]
登录进去是error

**Comment by kexirong** [comment]
> 登录进去是error

明显是钓鱼网站
